name: Build
on: push

jobs:
  build_on_win:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'skip-publish')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 15
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: install dependencies
        run: npm install
      - name: build react
        run: $env:CI=$false; npm run build;
      - name: publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run electron-ship
