name: Build
on: push

jobs:
  build_on_win:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'skip-publish')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: install dependencies
        run: npm install
      - name: build react
        run: $env:CI=$false; npm run build;
      - name: publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run electron-ship
